import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration 007 — Fix schema drift.
 * Brings the database in line with current entity definitions (Sprints 1-6).
 * Generated by `typeorm migration:generate --check` on 2026-04-12 and curated.
 *
 * Changes:
 *  - product.product_type: replace certification_types(jsonb) with certification_type(varchar),
 *    add hs_code + onssa_category, drop is_active (was in migration 002 but dropped from entity)
 *  - product.product: drop is_active column (dropped from entity)
 *  - cooperative.member: drop joined_at, add keycloak_user_id, fix column types
 *  - certification.inspection: add passed column, drop notes + deleted_at, fix status type
 *  - certification.inspection_report: add certification_id, cooperative_id, inspector_id,
 *    farm_findings, non_conformities, completed_at; drop findings, photos, filed_by, filed_at
 *  - certification.export_document: major restructure (add cooperative_id, consignee fields,
 *    valid_until, document_url, requested_by; drop document_type, document_number, issued_at,
 *    expires_at, created_by, deleted_at; fix destination_country length)
 *  - notification.notification_template: drop unique constraint + subject_template type change
 *  - Various FK + index cleanup
 */
export class FixSchemaDrift1700000000007 implements MigrationInterface {
  name = 'FixSchemaDrift1700000000007';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── Drop old FK constraints (will be re-added with TypeORM-managed names) ────
    await queryRunner.query(
      `ALTER TABLE "product"."lab_test" DROP CONSTRAINT IF EXISTS "lab_test_batch_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."lab_test_result" DROP CONSTRAINT IF EXISTS "lab_test_result_lab_test_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "cooperative"."farm" DROP CONSTRAINT IF EXISTS "farm_cooperative_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "cooperative"."member" DROP CONSTRAINT IF EXISTS "member_cooperative_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."qr_code" DROP CONSTRAINT IF EXISTS "qr_code_certification_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection" DROP CONSTRAINT IF EXISTS "inspection_certification_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP CONSTRAINT IF EXISTS "inspection_report_inspection_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP CONSTRAINT IF EXISTS "export_document_certification_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."certification_events" DROP CONSTRAINT IF EXISTS "fk_cert_events_certification"`,
    );

    // ── Drop indexes (TypeORM will recreate them) ────────────────────────────────
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_batch_cooperative_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_batch_product_type_code"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_batch_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_product_cooperative_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_product_type_code_ref"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_product_type_code"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_product_type_region"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_lab_test_batch_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_lab_test_cooperative_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_lab_test_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_lab_result_lab_test_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_lab_result_batch_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_lab_result_passed"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_harvest_farm_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_harvest_cooperative_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "product"."idx_harvest_campaign_year"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "notification"."idx_notification_recipient_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "notification"."idx_notification_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "notification"."idx_notification_trigger_event"`);
    await queryRunner.query(
      `DROP INDEX IF EXISTS "notification"."idx_notification_correlation_id"`,
    );
    await queryRunner.query(`DROP INDEX IF EXISTS "notification"."idx_template_code_channel_lang"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "cooperative"."idx_farm_cooperative_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "cooperative"."idx_farm_location"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "cooperative"."idx_cooperative_ice"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "cooperative"."idx_cooperative_region_code"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "cooperative"."idx_cooperative_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "cooperative"."idx_member_cooperative_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "cooperative"."idx_member_cin"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_qr_certification_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_qr_hmac_signature"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_qr_is_active"`);
    await queryRunner.query(
      `DROP INDEX IF EXISTS "certification"."idx_inspection_certification_id"`,
    );
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_inspection_inspector_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_inspection_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_report_inspection_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_export_certification_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_export_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_cert_cooperative_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_cert_batch_id"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_cert_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "certification"."idx_cert_type_region"`);
    await queryRunner.query(
      `DROP INDEX IF EXISTS "certification"."idx_cert_events_certification_id"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "certification"."idx_cert_events_correlation_id"`,
    );

    // ── notification.notification_template ───────────────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "notification"."notification_template" DROP CONSTRAINT IF EXISTS "notification_template_code_channel_language_key"`,
    );

    // ── product.product — drop is_active ────────────────────────────────────────
    await queryRunner.query(`ALTER TABLE "product"."product" DROP COLUMN IF EXISTS "is_active"`);

    // ── product.product_type — restructure ──────────────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" DROP COLUMN IF EXISTS "certification_types"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" DROP COLUMN IF EXISTS "is_active"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" ADD COLUMN IF NOT EXISTS "certification_type" character varying(20) NOT NULL DEFAULT 'IGP'`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" ALTER COLUMN "certification_type" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" ADD COLUMN IF NOT EXISTS "hs_code" character varying(20)`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" ADD COLUMN IF NOT EXISTS "onssa_category" character varying(50)`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" ALTER COLUMN "name_ar" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" ALTER COLUMN "lab_test_parameters" DROP DEFAULT`,
    );

    // ── cooperative.member — restructure ────────────────────────────────────────
    await queryRunner.query(`ALTER TABLE "cooperative"."member" DROP COLUMN IF EXISTS "joined_at"`);
    await queryRunner.query(
      `ALTER TABLE "cooperative"."member" ADD COLUMN IF NOT EXISTS "keycloak_user_id" uuid`,
    );
    await queryRunner.query(`ALTER TABLE "cooperative"."member" ALTER COLUMN "phone" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "cooperative"."member" DROP COLUMN IF EXISTS "role"`);
    await queryRunner.query(
      `ALTER TABLE "cooperative"."member" ADD COLUMN "role" character varying(20) NOT NULL DEFAULT 'member'`,
    );

    // ── cooperative.farm — type fixes ────────────────────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "cooperative"."farm" ALTER COLUMN "area_hectares" TYPE numeric(10,4)`,
    );
    await queryRunner.query(
      `ALTER TABLE "cooperative"."farm" ALTER COLUMN "latitude" TYPE numeric(10,6)`,
    );
    await queryRunner.query(
      `ALTER TABLE "cooperative"."farm" ALTER COLUMN "longitude" TYPE numeric(10,6)`,
    );

    // ── certification.inspection — restructure ───────────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection" DROP COLUMN IF EXISTS "notes"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection" DROP COLUMN IF EXISTS "deleted_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection" ADD COLUMN IF NOT EXISTS "passed" boolean`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection" ALTER COLUMN "inspector_name" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection" DROP COLUMN IF EXISTS "status"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection" ADD COLUMN "status" character varying(20) NOT NULL DEFAULT 'scheduled'`,
    );

    // ── certification.inspection_report — restructure ────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "findings"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "photos"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "filed_by"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "filed_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ADD COLUMN IF NOT EXISTS "certification_id" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ALTER COLUMN "certification_id" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ADD COLUMN IF NOT EXISTS "cooperative_id" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ALTER COLUMN "cooperative_id" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ADD COLUMN IF NOT EXISTS "inspector_id" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ALTER COLUMN "inspector_id" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ADD COLUMN IF NOT EXISTS "farm_findings" jsonb NOT NULL DEFAULT '[]'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ADD COLUMN IF NOT EXISTS "non_conformities" jsonb NOT NULL DEFAULT '[]'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ALTER COLUMN "completed_at" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" ADD CONSTRAINT "UQ_inspection_report_inspection_id" UNIQUE ("inspection_id")`,
    );

    // ── certification.export_document — restructure ──────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "document_type"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP CONSTRAINT IF EXISTS "export_document_document_number_key"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "document_number"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "issued_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "expires_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "created_by"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "deleted_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN IF NOT EXISTS "cooperative_id" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ALTER COLUMN "cooperative_id" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN IF NOT EXISTS "onssa_reference" character varying(50)`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN IF NOT EXISTS "consignee_name" character varying(200) NOT NULL DEFAULT ''`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ALTER COLUMN "consignee_name" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN IF NOT EXISTS "consignee_country" character varying(2) NOT NULL DEFAULT ''`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ALTER COLUMN "consignee_country" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN IF NOT EXISTS "valid_until" date`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN IF NOT EXISTS "document_url" character varying(500)`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN IF NOT EXISTS "requested_by" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ALTER COLUMN "requested_by" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "destination_country"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN "destination_country" character varying(2) NOT NULL DEFAULT ''`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ALTER COLUMN "destination_country" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ALTER COLUMN "hs_code" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ALTER COLUMN "quantity_kg" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "status"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN "status" character varying(20) NOT NULL DEFAULT 'draft'`,
    );

    // ── notification.notification_template — subject_template type fix ───────────
    await queryRunner.query(
      `ALTER TABLE "notification"."notification_template" ALTER COLUMN "language" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."lab_test_result" ALTER COLUMN "test_values" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "notification"."notification_template" DROP COLUMN IF EXISTS "subject_template"`,
    );
    await queryRunner.query(
      `ALTER TABLE "notification"."notification_template" ADD COLUMN "subject_template" character varying(300)`,
    );

    // ── certification.certification — default fix ────────────────────────────────
    await queryRunner.query(
      `ALTER TABLE "certification"."certification" ALTER COLUMN "current_status" SET DEFAULT 'DRAFT'`,
    );

    // ── Re-add FK constraints with TypeORM-managed names ────────────────────────
    await queryRunner.query(
      `ALTER TABLE "cooperative"."farm" ADD CONSTRAINT "FK_farm_cooperative_id" FOREIGN KEY ("cooperative_id") REFERENCES "cooperative"."cooperative"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "cooperative"."member" ADD CONSTRAINT "FK_member_cooperative_id" FOREIGN KEY ("cooperative_id") REFERENCES "cooperative"."cooperative"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "cooperative"."member" DROP CONSTRAINT IF EXISTS "FK_member_cooperative_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "cooperative"."farm" DROP CONSTRAINT IF EXISTS "FK_farm_cooperative_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."certification" ALTER COLUMN "current_status" SET DEFAULT 'pending'`,
    );
    await queryRunner.query(
      `ALTER TABLE "notification"."notification_template" DROP COLUMN IF EXISTS "subject_template"`,
    );
    await queryRunner.query(
      `ALTER TABLE "notification"."notification_template" ADD COLUMN "subject_template" character varying(500)`,
    );
    await queryRunner.query(
      `ALTER TABLE "notification"."notification_template" ALTER COLUMN "language" SET DEFAULT 'fr-MA'`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."lab_test_result" ALTER COLUMN "test_values" SET DEFAULT '{}'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "status"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN "status" character varying(30) NOT NULL DEFAULT 'pending'`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "destination_country"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" ADD COLUMN "destination_country" character varying(100)`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "requested_by"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "document_url"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "valid_until"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "consignee_country"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "consignee_name"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "onssa_reference"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."export_document" DROP COLUMN IF EXISTS "cooperative_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "completed_at"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "non_conformities"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "farm_findings"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "inspector_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "cooperative_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection_report" DROP COLUMN IF EXISTS "certification_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "certification"."inspection" DROP COLUMN IF EXISTS "passed"`,
    );
    await queryRunner.query(
      `ALTER TABLE "cooperative"."member" DROP COLUMN IF EXISTS "keycloak_user_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" DROP COLUMN IF EXISTS "onssa_category"`,
    );
    await queryRunner.query(`ALTER TABLE "product"."product_type" DROP COLUMN IF EXISTS "hs_code"`);
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" DROP COLUMN IF EXISTS "certification_type"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" ADD COLUMN "certification_types" jsonb NOT NULL DEFAULT '[]'`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product_type" ADD COLUMN "is_active" boolean NOT NULL DEFAULT true`,
    );
    await queryRunner.query(
      `ALTER TABLE "product"."product" ADD COLUMN "is_active" boolean NOT NULL DEFAULT true`,
    );
    await queryRunner.query(
      `ALTER TABLE "notification"."notification_template" ADD CONSTRAINT "notification_template_code_channel_language_key" UNIQUE ("code", "channel", "language")`,
    );
  }
}
